name: Publish Docker images

on:
  release:
    types: [published]

jobs:

  dev-ubuntu:
    runs-on: ubuntu-latest
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: a1russell/dev-ubuntu

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          target: dev_base_image
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=${{ runner.temp }}/dev-ubuntu.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dev-ubuntu
          path: ${{ runner.temp }}/dev-ubuntu.tar

  container-image-dev-ubuntu:
    runs-on: ubuntu-latest
    needs: dev-ubuntu
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dev-ubuntu
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/dev-ubuntu.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: a1russell/container-image-dev-ubuntu

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          target: docker_cli
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=${{ runner.temp }}/container-image-dev-ubuntu.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: container-image-dev-ubuntu
          path: ${{ runner.temp }}/container-image-dev-ubuntu.tar

  dind-ubuntu:
    runs-on: ubuntu-latest
    needs: container-image-dev-ubuntu
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: container-image-dev-ubuntu
          path: ${{ runner.temp }}

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/container-image-dev-ubuntu.tar

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: a1russell/dind-ubuntu

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./src
          target: docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
